"""
fetch_trades.py — Capitol Trades Scraper
========================================
Fetches the last 60 days of congressional stock trades for a given list of
politician IDs from capitoltrades.com and writes one output file:

  trade_data.json  — structured JSON keyed by member name (analysis-ready)

A timestamped copy is also written alongside it for change detection.

Usage
-----
1. Edit the POLITICIAN_IDS list below with the IDs you want to track.
   IDs follow the BioGuide format, e.g. "F000110", "K000389", "P000197".

2. Run:
       python fetch_trades.py

3. Optional flags:
       python fetch_trades.py --days 60       # change lookback window (default 90)
       python fetch_trades.py --out my_data   # change output filename prefix

Requirements
------------
    pip install requests
"""

import argparse
import json
import re
import sys
import time
from datetime import date, datetime, timedelta
from pathlib import Path

import requests

# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──
# CONFIGURE YOUR POLITICIAN IDs HERE
# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──
# Default member list — source of truth for the weekly report pipeline.
# Generated by scoring/score_members.py on 2026-04-09 (365d window, top-20
# stable picks after divergence filter). Re-run the scoring pipeline to
# refresh and copy the new list from scoring/output/default_follow_*.json.
POLITICIAN_IDS = [
    "C001047",    # Shelley Moore Capito         — R · Senate · WV
    "L000560",    # Richard Larsen               — D · House  · WA
    "F000479",    # John Fetterman               — D · Senate · PA
    "T000490",    # David Taylor                 — R · House  · OH
    "M001236",    # Timothy Moore                — R · House  · NC
    "M001218",    # Richard McCormick            — R · House  · GA
    "B001327",    # Robert Bresnahan             — R · House  · PA
    "M001222",    # Max Miller                   — R · House  · OH
    "S001229",    # Jefferson Shreve             — R · House  · IN
    "S001201",    # Thomas Suozzi                — D · House  · NY
    "K000389",    # Rohit Khanna                 — D · House  · CA
    "B001292",    # Donald Beyer                 — D · House  · VA
    "T000278",    # Thomas Tuberville            — R · Senate · AL
    "D000624",    # Deborah Dingell              — D · House  · MI
    "W000802",    # Sheldon Whitehouse           — D · Senate · RI
    "C001068",    # Stephen Cohen                — D · House  · TN
    "H001072",    # James Hill                   — R · House  · AR
    "C001129",    # Michael Collins              — R · House  · GA
    "H001082",    # Kevin Hern                   — R · House  · OK
    "K000375",    # William Keating              — D · House  · MA
]
# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──

BIOGUIDE_FILE = Path(__file__).parent / "member_bioguide.json"


def load_bioguide_directory() -> dict:
    """
    Load member_bioguide.json and return a lookup dict keyed by bioguide ID.
    Each entry exposes the most recent term so callers can resolve party,
    chamber, and state without scraping capitoltrades.
    """
    if not BIOGUIDE_FILE.exists():
        return {}
    try:
        with open(BIOGUIDE_FILE, "r", encoding="utf-8") as f:
            records = json.load(f)
    except Exception as exc:
        print(f"  ! Could not load {BIOGUIDE_FILE.name}: {exc}")
        return {}

    lookup: dict = {}
    for rec in records:
        bid = (rec.get("id") or {}).get("bioguide")
        if not bid:
            continue
        name = rec.get("name") or {}
        terms = rec.get("terms") or []
        last_term = terms[-1] if terms else {}
        chamber_raw = (last_term.get("type") or "").lower()
        chamber = "Senate" if chamber_raw == "sen" else "House" if chamber_raw == "rep" else ""
        lookup[bid] = {
            "bioguideId": bid,
            "firstName":  name.get("first", ""),
            "lastName":   name.get("last", ""),
            "fullName":   name.get("official_full") or f"{name.get('first','')} {name.get('last','')}".strip(),
            "party":      last_term.get("party", ""),
            "state":      last_term.get("state", ""),
            "chamber":    chamber,
        }
    return lookup


def resolve_politician_id(query: str, directory: dict) -> str | None:
    """Resolve a bioguide ID or a member name (case-insensitive) to a bioguide ID."""
    if not query:
        return None
    if query in directory:
        return query
    q = query.strip().lower()
    for bid, info in directory.items():
        if info["fullName"].lower() == q:
            return bid
    # last-name fallback (only if unique)
    matches = [bid for bid, info in directory.items() if info["lastName"].lower() == q]
    if len(matches) == 1:
        return matches[0]
    return None


BASE_URL = "https://www.capitoltrades.com/trades"
PAGE_SIZE = 96          # max the site supports
DELAY_SECS = 1.5        # polite delay between requests

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/122.0.0.0 Safari/537.36"
    ),
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
    "Referer": "https://www.capitoltrades.com/",
}


# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──
# RSC PARSING
# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──

def _extract_rsc_chunks(html: str) -> list[str]:
    """Return all decoded RSC payload strings from the page HTML."""
    chunks = []
    for m in re.finditer(
        r'self\.__next_f\.push\(\[(\d+),(".*?"|\[.*?\])\]\)',
        html,
        re.DOTALL,
    ):
        try:
            chunks.append(json.loads(m.group(2)))
        except Exception:
            pass
    return chunks


def _parse_trades_from_chunk(chunk: str) -> list[dict]:
    """
    Extract the raw trade objects from a single RSC chunk string.
    Returns an empty list if this chunk contains no trade data.
    """
    if '"_txId"' not in chunk:
        return []

    # The trade records sit inside a "data":[...] array within the RSC JSON tree.
    pos = chunk.find('"_txId"')
    start = chunk.rfind("[{", 0, pos)
    if start < 0:
        return []

    # Walk forward to find the closing ]} of the data array.
    depth = 0
    end = start
    for i, ch in enumerate(chunk[start:], start=start):
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                end = i + 1
                # Check if next non-space char closes the array
                rest = chunk[end:].lstrip()
                if rest.startswith("]"):
                    end = chunk.index("]", end) + 1
                    break

    raw = chunk[start:end]
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        # Attempt a lenient fallback using regex to pull individual objects
        objects = re.findall(r'\{[^{}]*"_txId"[^{}]*\}', raw)
        results = []
        for obj in objects:
            try:
                results.append(json.loads(obj))
            except Exception:
                pass
        return results


def _parse_pagination(chunks: list[str]) -> dict:
    """Extract totalCount and totalPages from any RSC chunk."""
    for chunk in chunks:
        if "totalPages" in chunk:
            m = re.search(r'"totalCount":(\d+),"totalPages":(\d+)', chunk)
            if m:
                return {
                    "totalCount": int(m.group(1)),
                    "totalPages": int(m.group(2)),
                }
    return {"totalCount": 0, "totalPages": 1}


def _parse_member_info(chunks: list[str]) -> dict:
    """Pull the politician name/party/chamber/state from the first page chunks."""
    for chunk in chunks:
        if '"_txId"' in chunk:
            m = re.search(
                r'"politician":\{"_stateId":"(?P<state>[^"]+)",'
                r'"chamber":"(?P<chamber>[^"]+)",'
                r'[^}]*"firstName":"(?P<first>[^"]+)",'
                r'[^}]*"lastName":"(?P<last>[^"]+)",'
                r'[^}]*"party":"(?P<party>[^"]+)"',
                chunk,
            )
            if m:
                return {
                    "firstName": m.group("first"),
                    "lastName": m.group("last"),
                    "chamber": m.group("chamber").title(),
                    "state": m.group("state").upper(),
                    "party": m.group("party").title(),
                }
    return {}


# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──
# FETCHING
# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──

def _fetch_page(politician_id: str, page: int) -> str:
    """Fetch one page of trade results and return the raw HTML."""
    url = (
        f"{BASE_URL}?politician={politician_id}"
        f"&pageSize={PAGE_SIZE}&page={page}"
    )
    response = requests.get(url, headers=HEADERS, timeout=20)
    response.raise_for_status()
    return response.text


def _normalise_trade(raw: dict) -> dict:
    """Convert a raw RSC trade object into our clean schema."""
    issuer = raw.get("issuer") or {}
    return {
        "txId":           raw.get("_txId"),
        "company":        issuer.get("issuerName"),
        "ticker":         issuer.get("issuerTicker"),
        "sector":         issuer.get("sector"),
        "txDate":         raw.get("txDate"),           # "YYYY-MM-DD"
        "published":      raw.get("pubDate", "")[:10], # truncate to date
        "filedAfterDays": raw.get("reportingGap"),
        "type":           (raw.get("txType") or "").upper(),
        "typeExtended":   raw.get("txTypeExtended"),
        "value":          raw.get("value"),             # mid-point $ estimate
        "price":          raw.get("price"),
        "owner":          raw.get("owner"),
        "comment":        raw.get("comment"),
    }


def fetch_member_trades(politician_id: str, cutoff_date: date, directory: dict | None = None) -> dict:
    """
    Fetch all trades for *politician_id* on or after *cutoff_date*.

    Returns a dict:
        {
            "bioguideId": str,
            "firstName": str,  "lastName": str,
            "chamber": str,    "state": str,    "party": str,
            "tradeCount": int,
            "trades": [...]
        }
    """
    print(f"\n  Fetching {politician_id}…", flush=True)
    all_trades: list[dict] = []
    total_pages = None
    member_info: dict = {}

    page = 1
    while True:
        print(f"    page {page}", end="")
        try:
            html = _fetch_page(politician_id, page)
        except requests.HTTPError as exc:
            print(f"  HTTP {exc.response.status_code} — stopping.")
            break

        chunks = _extract_rsc_chunks(html)

        # First page: capture member metadata and pagination
        if page == 1:
            member_info = _parse_member_info(chunks)
            pagination  = _parse_pagination(chunks)
            total_pages = pagination["totalPages"]
            total_count = pagination["totalCount"]
            print(f"  ({total_count} total trades, {total_pages} pages)", flush=True)
        else:
            print("", flush=True)

        raw_trades = []
        for chunk in chunks:
            raw_trades = _parse_trades_from_chunk(chunk)
            if raw_trades:
                break

        if not raw_trades:
            print("    No trades parsed on this page — stopping.")
            break

        # Normalise and filter to cutoff window
        stop_early = False
        for raw in raw_trades:
            tx_date_str = raw.get("txDate") or ""
            if tx_date_str:
                tx_date = date.fromisoformat(tx_date_str)
                if tx_date < cutoff_date:
                    stop_early = True
                    # Don't break — this page might have mixed dates;
                    # skip only trades older than cutoff
                    continue
            all_trades.append(_normalise_trade(raw))

        if stop_early:
            print("    Hit cutoff date — no need to fetch further pages.")
            break

        if page >= total_pages:
            break

        page += 1
        time.sleep(DELAY_SECS)

    # Sort by trade date descending
    all_trades.sort(key=lambda t: t["txDate"] or "", reverse=True)

    # Fall back to the local bioguide directory for any missing metadata.
    directory = directory or {}
    bio_info = directory.get(politician_id, {})
    for key in ("firstName", "lastName", "chamber", "state", "party"):
        if not member_info.get(key) and bio_info.get(key):
            member_info[key] = bio_info[key]

    full_name = (
        f"{member_info.get('firstName', '')} {member_info.get('lastName', '')}".strip()
        or bio_info.get("fullName")
        or politician_id
    )
    return {
        "bioguideId": politician_id,
        "fullName":   full_name,
        **member_info,
        "tradeCount": len(all_trades),
        "trades":     all_trades,
    }


# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──
# OUTPUT
# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──

def write_json(data: dict, path: Path) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"\n  JSON → {path}")


# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──
# MAIN
# ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ── ──

def main():
    parser = argparse.ArgumentParser(description="Fetch congressional trade data from capitoltrades.com")
    parser.add_argument("--days", type=int, default=60,
                        help="Lookback window in days (default: 60)")
    parser.add_argument("--out", default="trade_data",
                        help="Output filename prefix (default: trade_data)")
    parser.add_argument("--committee", default=None,
                        help="Committee name or thomas_id (e.g. 'House Committee on Armed Services' or 'HSAS'). "
                             "Overrides POLITICIAN_IDS and any IDs passed positionally.")
    parser.add_argument("ids", nargs="*",
                        help="Politician IDs to fetch (overrides the POLITICIAN_IDS list in the script)")
    args = parser.parse_args()

    # Load the local bioguide directory once; used for name→ID resolution
    # and as a metadata fallback when the scraper can't extract member info.
    directory = load_bioguide_directory()
    if directory:
        print(f"Loaded {len(directory)} members from {BIOGUIDE_FILE.name}")

    # Priority: --committee > positional IDs > hardcoded POLITICIAN_IDS.
    committee_summary = None
    if args.committee:
        from committee_lookup import describe_committee, resolve_committee
        committee_summary = describe_committee(args.committee)
        if not committee_summary or not committee_summary["bioguideIds"]:
            res = resolve_committee(args.committee)
            candidates = res.get("candidates", [])
            if candidates:
                print(f"ERROR: '{args.committee}' matched {len(candidates)} committees:")
                for c in candidates:
                    print(f"  {c.get('thomas_id','????'):<6} {c.get('name','')}")
                print("Re-run with the full committee name or thomas_id to disambiguate.")
            else:
                print(f"ERROR: Could not resolve committee '{args.committee}'.")
                print("Run `python3 committee_lookup.py --list` to see all committees.")
            sys.exit(2)
        print(f"Committee: {committee_summary['name']} ({committee_summary['thomas_id']}) — "
              f"{committee_summary['memberCount']} members")
        raw_inputs = committee_summary["bioguideIds"]
    else:
        raw_inputs = args.ids if args.ids else POLITICIAN_IDS

    # Naming: when a committee is used, embed its slug in the output prefix
    # so downstream artifacts don't collide with the default-list run.
    # Otherwise fall back to whatever was passed via --out (default "trade_data").
    if committee_summary and args.out == "trade_data":
        slug = re.sub(r"[^a-z0-9]+", "_", committee_summary["name"].lower()).strip("_")
        args.out = f"trade_data_{slug}"
        print(f"Output prefix: {args.out}")

    # CLI arguments may be either bioguide IDs or member names — resolve via the directory.
    ids_to_fetch: list[str] = []
    for entry in raw_inputs:
        resolved = resolve_politician_id(entry, directory) if directory else None
        if resolved:
            ids_to_fetch.append(resolved)
        else:
            # Pass through unchanged; assume caller supplied a bioguide ID
            ids_to_fetch.append(entry)
    if not ids_to_fetch:
        print("ERROR: No politician IDs provided.")
        print("Either add IDs to the POLITICIAN_IDS list in the script, or pass them as arguments:")
        print("  python fetch_trades.py F000110 K000389 P000197")
        sys.exit(1)

    cutoff = date.today() - timedelta(days=args.days)
    print(f"Fetching {args.days}-day trade window (since {cutoff}) for {len(ids_to_fetch)} member(s):")
    for pid in ids_to_fetch:
        print(f"  • {pid}")

    members: dict = {}
    for politician_id in ids_to_fetch:
        try:
            result = fetch_member_trades(politician_id, cutoff, directory)
            name_key = result["fullName"] or politician_id
            members[name_key] = result
            print(f"  ✓ {name_key}: {result['tradeCount']} trades in window")
        except Exception as exc:
            print(f"  ✗ {politician_id}: {exc}")
        time.sleep(DELAY_SECS)

    output = {
        "metadata": {
            "generated":       date.today().isoformat(),
            "window_days":     args.days,
            "cutoff_date":     cutoff.isoformat(),
            "source":          "capitoltrades.com",
            "members_tracked": len(members),
            "committee":       (
                {
                    "name":      committee_summary["name"],
                    "thomas_id": committee_summary["thomas_id"],
                }
                if committee_summary else None
            ),
        },
        "members": members,
    }

    from datetime import datetime
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")

    data_dir = Path(__file__).parent / "data"
    data_dir.mkdir(parents=True, exist_ok=True)

    # Current file (overwritten each run — used by the analysis pipeline)
    write_json(output, data_dir / f"{args.out}.json")

    # Timestamped archive copy in data/ (used by change detection)
    write_json(output, data_dir / f"{args.out}_{ts}.json")

    # Summary table
    print("\n" + "─" * 60)
    print(f"{'Member':<30} {'Party':<12} {'Trades':>6}")
    print("─" * 60)
    for name, d in members.items():
        print(f"{name:<30} {d.get('party',''):<12} {d['tradeCount']:>6}")
    print("─" * 60)
    total = sum(d["tradeCount"] for d in members.values())
    print(f"{'TOTAL':<43} {total:>6}")
    print()

    # Hint for downstream pipeline so the agent knows which file to feed in.
    stats_out = args.out.replace("trade_data", "computed_stats")
    skel_out  = args.out.replace("trade_data", "analysis_skeleton")
    anly_out  = args.out.replace("trade_data", "analysis")
    print("Next steps:")
    print(f"  python3 compute_analysis.py --in data/{args.out}.json --out computed_stats/{stats_out}.json")
    print(f"  python3 build_skeleton.py    --in computed_stats/{stats_out}.json --out analysis_skeleton/{skel_out}.json")
    print(f"  # then fill placeholders into analysis/{anly_out}.json and:")
    print(f"  python3 generate_report.py analysis/{anly_out}.json")
    print()


if __name__ == "__main__":
    main()
