"""
_record.py — one-shot fixture regenerator for the pytest suite.

Not run in CI. Not discovered by pytest (leading underscore). Invoke by
hand when the underlying capitoltrades API schema drifts or when the
committed fixtures go stale:

    python3 tests/fixtures/_record.py

Reads the locally-populated `scoring/cache/` directory (which
capitoltrades + yfinance write into during normal monthly scoring runs)
and downsamples a committable slice into `tests/fixtures/`.

Does NOT hit capitoltrades or yfinance directly. Sampling from the
already-materialized cache sidesteps the sandbox network-allowlist risk
flagged in `design/pytest-ci-suite.md`: if the cache is populated (it is,
after any scoring run), this script works without network.

Outputs:
    tests/fixtures/capitoltrades_page_sample.json  — one member, 10 trades
    tests/fixtures/prices/{TICKER}.csv             — 10 tickers × ~2yr closes
    tests/fixtures/member_bioguide_sample.json     — 5 members, mixed parties

`synthetic_alpha_scenarios.py` is hand-crafted (edge cases, not real
data) and is NOT regenerated by this script.
"""

from __future__ import annotations

import json
import random
import shutil
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
TRADE_CACHE = REPO / "scoring" / "cache" / "trades"
PRICE_CACHE = REPO / "scoring" / "cache" / "prices"
BIOGUIDE = REPO / "member_bioguide.json"

OUT_TRADES = HERE / "capitoltrades_page_sample.json"
OUT_PRICES = HERE / "prices"
OUT_BIOGUIDE = HERE / "member_bioguide_sample.json"

# Deterministic sampling.
random.seed(20260421)

# Target tickers: common, covers enough breadth for alpha-math tests plus
# a benchmark. Must all be present in scoring/cache/prices/.
TARGET_TICKERS = ["AAPL", "MSFT", "NVDA", "GOOGL", "AMZN",
                  "META", "TSLA", "JPM", "XOM", "SPY"]

# Trade selection: pick a member whose cache is large enough that we can
# downsample to a diverse 10-record slice. K000389 (Ro Khanna) is the
# canonical anchor used elsewhere in the pipeline.
TARGET_MEMBER = "K000389"
TARGET_TRADE_COUNT = 10


def _pick_diverse_trades(trades: list[dict], n: int) -> list[dict]:
    """Deterministically pick n trades that cover varied types/owners/tickers.

    Heuristic: sort by txId for determinism, then greedily pick one record
    per (type, owner) pair first, then fill remainder with evenly-spaced
    records from what's left.
    """
    trades = sorted(trades, key=lambda t: t.get("txId") or 0)
    seen_pairs: set[tuple] = set()
    picked: list[dict] = []
    for t in trades:
        pair = (t.get("type"), t.get("owner"))
        if pair not in seen_pairs and len(picked) < n:
            seen_pairs.add(pair)
            picked.append(t)
    if len(picked) < n:
        remaining = [t for t in trades if t not in picked]
        step = max(1, len(remaining) // max(1, n - len(picked)))
        picked.extend(remaining[::step][: n - len(picked)])
    return picked[:n]


def record_trades() -> None:
    src = TRADE_CACHE / f"{TARGET_MEMBER}.json"
    if not src.exists():
        raise FileNotFoundError(
            f"Trade cache not found: {src}. "
            f"Run the scoring pipeline locally or in GHA first to populate it."
        )
    with src.open() as f:
        blob = json.load(f)
    full_trades = blob["data"].get("trades", [])
    picked = _pick_diverse_trades(full_trades, TARGET_TRADE_COUNT)
    slim = {
        "fetched_at": blob["fetched_at"],
        "window_days": blob["window_days"],
        "data": {
            **{k: v for k, v in blob["data"].items() if k != "trades"},
            "tradeCount": len(picked),
            "trades": picked,
        },
    }
    OUT_TRADES.write_text(json.dumps(slim, indent=2) + "\n")
    print(f"  wrote {OUT_TRADES.relative_to(REPO)} ({len(picked)} trades)")


def record_prices() -> None:
    OUT_PRICES.mkdir(exist_ok=True)
    # Note: orphan CSVs from prior runs (i.e. tickers removed from
    # TARGET_TICKERS) are left in place. `rm` fails on this FUSE mount,
    # and orphans don't break any test. Clean them by hand if it matters.
    copied = 0
    missing: list[str] = []
    for ticker in TARGET_TICKERS:
        src = PRICE_CACHE / f"{ticker}.csv"
        if not src.exists():
            missing.append(ticker)
            continue
        shutil.copy2(src, OUT_PRICES / f"{ticker}.csv")
        copied += 1
    print(f"  wrote {copied} ticker CSVs to {OUT_PRICES.relative_to(REPO)}")
    if missing:
        print(f"  WARN: missing in price cache: {missing}")


def record_bioguide() -> None:
    with BIOGUIDE.open() as f:
        members = json.load(f)
    # `id` is a dict keyed by external identifier system (bioguide, thomas,
    # govtrack, etc.); sort by the bioguide id for determinism.
    def _bio(m: dict) -> str:
        idblock = m.get("id") or {}
        return idblock.get("bioguide") or "" if isinstance(idblock, dict) else ""

    members_sorted = sorted(members, key=_bio)
    step = max(1, len(members_sorted) // 5)
    sample = members_sorted[::step][:5]
    OUT_BIOGUIDE.write_text(json.dumps(sample, indent=2) + "\n")
    print(f"  wrote {OUT_BIOGUIDE.relative_to(REPO)} ({len(sample)} members)")


def main() -> None:
    print("Regenerating pytest fixtures from scoring/cache/ and member_bioguide.json...")
    record_trades()
    record_prices()
    record_bioguide()
    print("Done. Review diffs before committing; the recorder is deterministic "
          "but upstream schema drift still merits a human pass.")


if __name__ == "__main__":
    main()
